### ISSUE TITLE
`Select` doesn't properly highlight the selected option once it is filtered

### ISSUE THREAD

**Issue by prime31** [mikaelmello/inquire#106]
**Describe the bug**
`Select` doesn't properly highlight the selected option once it is filtered

**To Reproduce**
1. run the `select` example
2. type the letter 'g'
3. notice that the prompt is on the "Grapes" but it is not colored blue

**Expected behavior**
The expected behavior is that the element at the prompt is always colored blue. In the screenshot that would be the word "Grapes"

**Screenshots**
<img width="359" alt="Screenshot 2023-03-19 at 3 30 19 PM" src="https://user-images.githubusercontent.com/60377/226213905-79c620d6-1611-455b-98a1-17f741cc183f.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - 13.2.1 (22D68)

**Comment by mikaelmello** [comment]
Thanks for the catch! I'll work on it.
