### ISSUE TITLE
How Do I Write An Integration Test For Inquire (Confirm)?

### ISSUE THREAD

**Issue by JimLynchCodes** [mikaelmello/inquire#107]
I have a little cli tool that basically asks the user a yes or no question and then prints a response to the console.

Here is what I currently have:

```rust
#[test]
fn always_works() -> Result<(), Box<dyn std::error::Error>> {
    let mut cmd = Command::cargo_bin("mybin")?;
    
    cmd.assert().success();

    Ok(())
}
```

This always works, and I don't really know how to do any assertions...

Is it possible for me to pass some `.arg("--yes")` or `.arg("--no")` that will simulate a user responding to the prompt?

Also, is there any way for me to assert that the proper question, prompt and response text is output in the console?

Thanks! 🙏

**Comment by JimLynchCodes** [comment]
Note, I also asked this on SO: https://stackoverflow.com/questions/75816676/how-can-i-write-integration-tests-for-a-rust-cli-tools-that-use-inquire

**Comment by JimLynchCodes** [comment]
I think this issue[this issue](https://github.com/mikaelmello/inquire/issues/40)  may be related… not sure how exactly I use this Key struct to simulate hitting the enter key in my test though. 🤔

**Comment by JimLynchCodes** [comment]
Hmmm I tried to use the cfg macros to control the color choice, but actually this doesn't even work because for integration tests it should use the `#[cfg(not(test))]` one... 🤔

```
   let table = vec![
        vec!["Tom".cell(), 10.cell().justify(Justify::Right)],
        vec!["Jerry".cell(), 15.cell().justify(Justify::Right)],
        vec!["Scooby Doo".cell(), 20.cell().justify(Justify::Right)],
    ]
    .table()
    .title(vec![
        "Name".cell().bold(true),
        "Age (in years)".cell().bold(true),
    ])
    .color_choice(get_color_choice())     // <--- new thing
    .bold(true);
```

#[cfg(not(test))]
fn get_color_choice() -> ColorChoice {
    ColorChoice::Auto
}

#[cfg(test)]
fn get_color_choice() -> ColorChoice {
    ColorChoice::Never
}
```

**Comment by mikaelmello** [comment]
Working on making this possible, tracked on #71
