### ISSUE TITLE
Duplicated key input when running examples on Windows

### ISSUE THREAD

**Issue by fdncred** [mikaelmello/inquire#132]
**Describe the bug**
I'm trying the examples and getting odd behavior that prevents the examples from working properly.

**To Reproduce**
1. Below you can see how I compiled an ran.
2. I did not hit any key after compilation and it automatically fills in "No" for the first answer.
3. I try to type `y` on the next question and what prints to the screen is `yy`.
4. Any example that requires typing input comes out as doubled for each key you type.
```
cargo r --example confirm
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
     Running `c:\cartar\debug\examples\confirm.exe`
> Do you live in Brazil? No
Your answer: false
? Do you want to move to another country? yy
```

**Expected behavior**
The keystrokes printed to the screen match what I type.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by mikaelmello** [comment]
Thanks for the report, I spun up a Windows VM and could reproduce the issue. I'll investigate ASAP

**Comment by mikaelmello** [comment]
I've identified the root cause which was upgrading crossterm to v0.26, and reverted the change.

Can you check if the problem is resolved on your end?

**Comment by mikaelmello** [comment]
For tracking purposes, these are the related issues on crossterm:

https://github.com/crossterm-rs/crossterm/issues/772
https://github.com/crossterm-rs/crossterm/issues/752
https://github.com/crossterm-rs/crossterm/pull/778

**Comment by fdncred** [comment]
The revert fixed it for me. Thanks!
