### ISSUE TITLE
Cursor Wonkiness When Using Console In Help Message

### ISSUE THREAD

**Issue by JimLynchCodes** [mikaelmello/inquire#135]
So, the project I've been working on is a little cli tool to play a game like [wordle](https://www.nytimes.com/games/wordle/index.html) right in the terminal.

I am using a [Text](https://github.com/mikaelmello/inquire#Text) input from the inquire crate to accept input from the user.

I'm also using the [console](https://crates.io/crates/console) crate to print out the remaining letters of the "keyboard" and highlight them to show if they have been guessed already and if they are in the word, correct position, etc.

I am also using some other crates for the generation of secret word and validation of guesses, but I don't think they are relevant to the console output wonkiness...

So, everything technically works right now, but the weird part is that when I start typing my whole prompt shifts up one line in my terminal. It's super weird and I'm not sure if the bug is caused by inquire, or console, or the two of them together, or the fact that I'm using all these things in the "help message" of my text input, or if it's just a unix thing...

It's hard to explain so I made this gif to try what I mean:

![wonky-console-text-input](https://user-images.githubusercontent.com/5354163/234626117-be66cfe5-233a-4e00-ad14-3b8d77c49139.gif)

This project lives in the "wip_wordle_game" directory within [this repo](https://github.com/JimLynchCodes/rust-cli-examples/tree/wonky-console-output/wip_wordle_game). Feel free to take a look at the code and / or run it yourself with cargo run.

I'm looking for any advice on what I should try and / or insight into why this wonkiness is happening.

In the inquire docs it says, "You can choose your terminal backend between crossterm (default), termion or console".

I can try to reimplement the coloring using crossterm or termion, but I am very curious what's going on here with the console crate...

Thanks!

**Comment by JimLynchCodes** [comment]
I think it is definitely some kind of issue with using "console" in the help message.

When I replace the help message text with some hardcoded string the wonkiness is gone...

**Comment by LeoRiether** [comment]
I've investigated a bit and found that this is, indeed, wonky. I can reproduce the same wonky behavior with this help message

![the alphabet but shorter](https://user-images.githubusercontent.com/8211902/234695015-eee49059-018f-4cac-8da6-5799b08b68fa.png)

but if I print only until `k`, it's completely fine. I'd say this is probably a bug in inquire's way of calculating the displayed width of the help message.

Thanks for the report :)

**Comment by JimLynchCodes** [comment]
Yep, I just tried using `termion` to style the text rather than `console`, but I'm seeing the same wonky behavior. 😢

Maybe one of the authors like @mikaelmello can confirm that the Text input is not meant to support colorized text like this and possibly give us some insight on how we can make this not wonky? 🤔

**Comment by mikaelmello** [comment]
>Maybe one of the authors like @mikaelmello can confirm that the Text input is not meant to support colorized text like this and possibly give us some insight on how we can make this not wonky? 🤔

I wanted to cover all customization via a unified API so that's why we have RenderConfigs and a StyleSheet API and everything, but yeah it ended up kinda limiting so something like what you built isn't possible via inquire's API.

From that history, I've never thought of stripping ANSI codes when processing custom messages lol, but it is clearly a bug and we're fixing it!

**Comment by JimLynchCodes** [comment]
@LeoRiether  @mikaelmello  ermagerd, thanks yall! 🙏

I just opened up my project, ran `cargo update -p inquire`, and started it up again.

The wonkiness is gone!!

ty 🥹
