### ISSUE TITLE
Possible password confirmation unhappy path endless loop.

### ISSUE THREAD

**Issue by CM-IV** [mikaelmello/inquire#149]
**Describe the bug**
Upon entering a password and then re-entering a password that does not match during confirmation leads me to an endless loop of `# The answers don't match`.  The prompt seems to ask correctly for the password again, but once it is entered this time with matching information, the same result is reached.

![image](https://github.com/mikaelmello/inquire/assets/44551614/0d5bd9d6-793c-4523-98cf-039ab82e9e41)

**To Reproduce**
Start with a bone dry cargo init project with `inquire` and `anyhow` installed for errors.

![image](https://github.com/mikaelmello/inquire/assets/44551614/33ae87a9-f3ef-4211-84c5-bb52dc717ea2)
![image](https://github.com/mikaelmello/inquire/assets/44551614/ce0316fd-1a0e-40c0-9e86-f66e4ce4ab06)

**Expected behavior**
Once an incorrect password is entered in confirmation, the user is alerted that `# The answers don't match`.  However, the user should(?) be able to re-enter both the password and confirm-password to get back to the happy path and print `End` to the terminal.

**Desktop (please complete the following information):**
 - OS: Debian 12 Bookworm
 - Browser: Firefox 102.12.0esr (64-bit)
 - rustup: 1.26.0
 - rustc: 1.70.0

**Comment by mikaelmello** [comment]
Working on it!
