### ISSUE TITLE
Editer can't capture the data..

### ISSUE THREAD

**Issue by Sanjuvi** [mikaelmello/inquire#175]
```rust
let emails = Editor::new("Enter the each emails")
                  .with_help_message("Each email is should separated by space or new line")
                  .prompt()
                  .unwrap();

let email_from_strings = emails.lines().collect::<Vec<_>>();
println!("{email_from_strings:?}");

//output is <skipped>
[]
```
"Why isn't this working? I press 'e,' which then opens the Notepad. I enter each email on a new line, save it, and finally input it in the command line. However, I receive an empty output. Why? A quick answer would be greatly appreciated as I am working on a project."

**Comment by Baarsgaard** [comment]
Did you enable the `editor` feature in your `Cargo.toml`?
It's disabled by default.

```toml
inquire = {version = "0.6.2", features = ["editor"] }
```

**Comment by mikaelmello** [comment]
Hey @Sanjuvi, I'm sorry I wasn't able to provide the quick answer you wanted, I haven't been able to give the attention I wanted to inquire but I'm hoping to get back on track now.

Looking at your [Simple-Email-Service-SES-Client](https://github.com/Sanjuvi/Simple-Email-Service-SES-Client) repo, it looks like the problem may have been solved? I'm going to close the issue but feel free to reopen it if you still see the problem.
