### ISSUE TITLE
Use tty instead of stdin

### ISSUE THREAD

**Issue by cloudhead** [mikaelmello/inquire#192]
When trying to read from a process that has input piped into its stdin, `inquire` returns an error, saying stdin is not a TTY. In those cases, we should be reading directly from the `tty` device. Basically something like this:

```rust
        let stdin = if io::stdin().is_terminal() {
            process::Stdio::inherit()
        } else {
            let tty = termion::get_tty()?;
            // In that case, we use the terminal device, eg. `/dev/tty` as standard input.
            process::Stdio::from(tty)
        };
```

If this isn't something you want to do in inquire, an alternative would be to be able to specify a backend, or input stream, eg. `prompt_with_stream(io: process::Stdio)`.

**Comment by mikaelmello** [comment]
Hey, I've fixed that for termion, but overall cross-platform support is a long story, see #198 :)
