### ISSUE TITLE
Implement "multiline" prompt

### ISSUE THREAD

**Issue by mikaelmello** [mikaelmello/inquire#2]
Motivation looks similar to #1, the idea here is to allow the user to input a multi-line text without having to open a text editor.

Not sure how useful this would be, as I consider #1 more important.

Edit: this is now activelly not planned to be implemented by the maintainer (me...). I'll be leaving this open in case anyone is interested in implementing it.

**Comment by VladimirMarkelov** [comment]
It won't be easy if you are going to keep the package crossplatform.

Maybe this one can be a source of inspiration: https://github.com/Avarel/mini-me

**Comment by mikaelmello** [comment]
>It won't be easy if you are going to keep the package crossplatform.

Can't say I have much experience on that front, what kind of challenges are you expecting?

I thought it would be pretty standard stuff, just a lot of work.

Anyway, probably another reason to prefer editor support over this :)

**Comment by VladimirMarkelov** [comment]
When I was writing my comment, I did not know yet that you had already used `crossterm` package. It is already crossplatform and it makes my comment unrelated.

I agree, editor support is good to have as well. I'm fine with calling an editor to type long text - I do it to enter multi-line git comments.  :)

**Comment by gopherine** [comment]
would love to see this feature ... I have a use case where i need to write few bullet points , but opening an editor to do this feels really unnatural

**Comment by mikaelmello** [comment]
@gopherine unfortunately it isn't in our plans due to how complex a multi-line editor would be

I'd gladly review any PRs but it should be a lot of work to implement it right and I unfortunately don't have the time atm

**Comment by mikaelmello** [comment]
Unfortunately there isn't really much of a point in keeping this open. Even Github's CLI uses a text editor for larger inputs.

The point about accepting it if someone implements stays :)
