### ISSUE TITLE
inquire derive and attribute macro

### ISSUE THREAD

**Issue by simonsan** [mikaelmello/inquire#212]
I would like to easily annotate a configuration struct, to ask the user for input for various fields and give a hint on validation:

```rust

use inquire::AskUser;

#[derive(Debug, AskUser)]
struct MyConf {
    #[ask(q="Please enter password:", hide_input=true, min_len=12)]
    password: Option<String>,

    #[ask(q="Please enter username:", min_len=3)]
    username: Option<String>,

    #[ask(q="Please enter age:", range=18..=85)]
    age: Option<u8>,
}

fn main() -> Result<()> {
    let mut conf = MyConf::default()
    conf.password()?.validate()?;
    conf.username()?.validate()?;
    conf.age()?.validate()?;

    println!("{conf#?}");
}
```

I would be interested if something like this is already existing, e.g. based on inquire, or if there is any interest to add this?

**Comment by IniterWorker** [comment]
I will close this one, but please feel free to comment on https://github.com/mikaelmello/inquire/issues/65. I don't have much time to work these days.
