### ISSUE TITLE
Render issue using the `console` backend

### ISSUE THREAD

**Issue by maospr** [mikaelmello/inquire#228]
**Describe the bug**
When using `inquire` with the `console` backend to present a select, the select options disappear from screen upon interaction (typing, arrow down).
But the options are still there. Making a now invisible selection still yields the right result. Just the rendering of options is gone.

Using the `termion` & `crossterm` backends still work fine.

**To Reproduce**
Switch to the `console` backend:
```toml
[dependencies]
inquire = { version = "0.7.0", default-features = false, features = [ "console" ] }
```
Run the cli tool.

**Expected behavior**
I expected to see a change in selection upon pressing navigating (up/down) or a change of options when filtering.

**Screenshots**
Left: `console`, Right: `termion`
![image](https://github.com/mikaelmello/inquire/assets/29260882/20c43bac-676b-4769-b2c8-b676530f2ae4)

And output result:
![image](https://github.com/mikaelmello/inquire/assets/29260882/760b739b-21d1-4d5d-9b35-28bddd00b2a9)

**Desktop (please complete the following information):**
 - OS: FreeBSD 14 & Debian 12 (bookworm)
 - Terminal: alacritty 0.13.0
 - Version: 0.7.0

**Additional context**
Version 0.6.2 of `inquire` still worked fine with the `console` backend.
Sample project demonstrating this behavior: https://github.com/maospr/inquire-render-issue

**Comment by mikaelmello** [comment]
Thanks for the report, fixing it!
