### ISSUE TITLE
Use terminal cursor in text prompts

### ISSUE THREAD

**Issue by mikaelmello** [mikaelmello/inquire#23]
**Is your feature request related to a problem? Please describe.**

The cursor in text prompts is entirely artificial, we explicitly add a background and foreground colors on where the cursor should be. Meanwhile, the actual cursor is hidden at the end of the prompt.

Ideally, we should position the cursor where it should actually reside. I'm not sure if this helps with accessibility, it would be even more worth it if it does.

**Describe the solution you'd like**

The backend should mark where the cursor should be and move it to the correct place after rendering the entire prompt.

**Comment by mikaelmello** [comment]
Yeah, apparently this won't work unless I give up supporting Emoji ZWJ Sequences.

i can move the terminal's cursor based on rows and columns. This usually works because it is quite easy to predict the length your text will take. If I'm not printing anything fancy I can be more or less confident that all characters (e.g. those in ASCII) will render in one column each.

This doesn't hold for ZWJ sequences. They can take an arbitrary number of columns depending on which terminal/platform inquire is running on. For example: 👨🏼‍🦰, which is combining 👨 Man, 🏼 Medium-Light Skin Tone, ‍ Zero Width Joiner and 🦰 Red Hair. [source](https://emojipedia.org/man-medium-light-skin-tone-red-hair/).

`unicode_segmentation` correctly counts 1 grapheme. However, my terminal does not support this grapheme, rendering 3 things instead: 
![](https://user-images.githubusercontent.com/17488630/131236993-143be0c8-5ba2-4170-83fd-b44b6bf3fbbf.png)

From the level of inquire, it is ~impossible~ not trivial to know how much columns a grapheme will take. Thus, when working with string lengths to position the cursor on the correct column, I probably know in which column the "man" emoji is being rendered, but I can't know if the `c` after the emoji is 1 or 3 columns to the right.

With the current approach, an "artificial" cursor where I manually color the background, this works because I'm always rendering an entire grapheme at the cursor (which means a light background). Resulting in this:
![2021-08-29_00-17](https://user-images.githubusercontent.com/17488630/131237074-11b346b8-d4ed-4f1e-a75c-7cf90400f854.png)

It's not the works-perfectly approach, as 3 visual chars are treated as 1, but positioning the cursor will consistently work across any platform.

For now, I'll just position the cursor at wherever I imagine the graphemes will be (always assuming 1 grapheme occupies 1 column). However, I'll keep hiding the native cursor and use the artificial one. The issue will stay open.

**Comment by mikaelmello** [comment]
For the record, I also considered using the native cursor when the input is empty, where its behavior would be to always highlight the first rendered char.

This would also not work because EJW on prompt messages would mess with the columns anyway =/

**Comment by mikaelmello** [comment]
The main trade-off when implementing this feature was to have the cursor in a non-expected place between frames. If the user canceled the operation or any error happened when the cursor was not at the end of the prompt, I would have to move it back to the end when dropping Backend, which is a fallible operation, possibly leaving users with a corrupted state (mis-positioned cursor).

**Comment by mikaelmello** [comment]
After some consideration, I've decided to continue to use native cursors even if they do not work with these edge cases. I've checked the behavior of `dialoguer` in this scenario and it breaks as well, so we'll not be missing something other libs have

**Comment by mikaelmello** [comment]
Correction: it's not only EJW that break, but any kind of emoji because they take 2 columns in the terminal, while we are only counting one.

**Comment by mikaelmello** [comment]
Even better, we will be following rustc's approach to assume the width of characters via unicode params, with help from the `unicode_width` crate. It seems to work perfect on my terminal

**Comment by mikaelmello** [comment]
Closed via https://github.com/mikaelmello/inquire/commit/cd7874a8f20517ad058af07402f78b6fffe21579

**Comment by pronebird** [comment]
Doesn't work properly for 👨‍💼 emoji. The cursor is way ahead of entered text when filtering from keyboard
