### ISSUE TITLE
Inquire forgets to add newlines in 0.7.1

### ISSUE THREAD

**Issue by msrd0** [mikaelmello/inquire#233]
**Describe the bug**

I just upgraded from 0.6.2 to 0.7.1. Suddenly, all prompts overwrite the previous prompt, as if there is a newline missing.

**To Reproduce**
1. Add inquire dependency 0.7 with default features 
2. Call `CustomType::...::prompt()`
3. Answer the prompt
4. Call another prompt
5. See error

**Expected behavior**
I expect a newline to be added to the previous prompt, so that the next prompt does not overwrite the previous one.

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - ~~Browser~~ Terminal: alacritty
 - Version: 0.7.1 (0.7 is broken as well)

**Comment by mikaelmello** [comment]
Hey, I haven't been able to reproduce the issue, can you give me more details? Maybe a repo that reproes the issue

This may be limtied to Alacritty, but unfortunately I can't try alacritty right now as it seems the Mac installer has some issues, but my tests have been fine on both Mac and Ubuntu (via SSH) systems.

**Comment by Sydonian** [comment]
I encountered the same problem, and below are my test codes:
``` rust
use inquire::Text;

fn main() {
    loop {
        match Text::new(">>").prompt() {
            Ok(text) => println!("{}", text),
            Err(e) => println!("Error: {}", e),
        }
    }
}

```
I noticed that if I run the program and just press enter key about 12 times, then it will lose the newline after the echos of my input:

![20240316165819](https://github.com/mikaelmello/inquire/assets/26449503/53f87158-0715-4dfc-b328-2b8bbaa0687f)

I'm using Windows 11,  and I have tried it on PowerShell and CMD,  and both appear the same problem and even the CMD only need 11 enter keys.

**Comment by mikaelmello** [comment]
Thanks @Sydonian, I was able to reproduce the issue after the "press enter until it happens" advice.

No idea how this even works half the time, but from my tests when it reached the "broken state" it stayed like that.

Looks like the issue is because the new rendering logic ignores empty lines.

Can you pleae test the fix?

```toml
[dependencies]
inquire = { git = "https://github.com/mikaelmello/inquire.git", branch = "mm/fix-new-line-prompt-end" }
```

**Comment by Sydonian** [comment]
> Thanks @Sydonian, I was able to reproduce the issue after the "press enter until it happens" advice.
> 
> No idea how this even works half the time, but from my tests when it reached the "broken state" it stayed like that.
> 
> Looks like the issue is because the new rendering logic ignores empty lines.
> 
> Can you pleae test the fix?
> 
> ```toml
> [dependencies]
> inquire = { git = "https://github.com/mikaelmello/inquire.git", branch = "mm/fix-new-line-prompt-end" }
> ```

I tried this on the test program and my project, both work fine, thank you!

**Comment by msrd0** [comment]
Can also confirm the branch works. I always accepted the default value for the first prompt, so the bug always triggered for me.
