### ISSUE TITLE
MultiSelect list doesn't show after filter is cleared on selection

### ISSUE THREAD

**Issue by Swivelgames** [mikaelmello/inquire#238]
**Describe the bug**
When using the `MultiSelect`, after a selection is made using the filter and the filter clears, the list doesn't reset. It requires the user to type and clear the filter manually to be able to see the whole list again.

**To Reproduce**
1. Implement a MultiSelect
2. Run your program
3. When you get to a `MultiSelect` Prompt, type in to filter the list
4. Select an item

**Expected behavior**
When the filter clears, the list should show all items again.

**Actual behavior**
Notice the filter clears, but the list doesn't reset. Typing in to filter the list again and deleting the filter manually then shows the whole list again.

**Screenshots**

1. Initial List
![image](https://github.com/mikaelmello/inquire/assets/1456302/f3e31620-0fa4-4cdb-bf48-d6a24b48b79c)

2. Filter the list
![image](https://github.com/mikaelmello/inquire/assets/1456302/2669a58a-0a0d-42ed-b7a3-78db33cb7339)

3. Select an item (filter clears, but list doesn't reset)
![image](https://github.com/mikaelmello/inquire/assets/1456302/f17fdfcf-2dea-4ffc-a61b-49f68cbb3da8)

4. Filter the list again
![image](https://github.com/mikaelmello/inquire/assets/1456302/eeecb42e-74c2-4fcd-967a-a67061c8bf52)

5. Backspace the filter to show the whole list again
![image](https://github.com/mikaelmello/inquire/assets/1456302/026e1e93-a911-46ff-b606-ed9340a87471)

**Comment by mikaelmello** [comment]
Fixed on v0.7.4 :)

Thanks for reporting
