### ISSUE TITLE
Suggestions not updated after autocomplete

### ISSUE THREAD

**Issue by moritz-hoelting** [mikaelmello/inquire#257]
**Describe the bug**
When you press tab to autocomplete, the shown suggestions are not updated 

**To Reproduce**
1. Run the `complex_autocompletion` example
2. Select a folder and press tab

**Expected behavior**
The folder path is autocompleted and the suggestions show the entries of the new folder (currently showing the entries of the previously selected folder)

**Comment by mikaelmello** [comment]
Fixed on https://github.com/mikaelmello/inquire/commit/398ea88680f2c3a565db887f5ed42a5299ae1e3d, should go out on v0.7.6.
