### ISSUE TITLE
MultiSelect without requirement to implement Display

### ISSUE THREAD

**Issue by istudyatuni** [mikaelmello/inquire#269]
**Is your feature request related to a problem? Please describe.**
I want to select paths, but PathBuf doesn't implement Display, but it has display() method

**Describe the solution you'd like**
Allow creating MultiSelect when elements doesn't implement Display, but if you provide custom formatter. Maybe something like
```rs
MultiSelect::new_with_formatter("text", [paths, ...], &|p| p.display()).prompt()?;
```

**Describe alternatives you've considered**

\-

**Additional context**

\-

**Comment by Baarsgaard** [comment]
You should be able to wrap a PathBuf in a newtype and implement Display for it quite easily:
```rust
use std::{fmt::Display, path::PathBuf, str::FromStr};

fn main() {
    let path = PathBuf::from_str("/home").unwrap();

    println!("{}", DisplayPathBuf(path));
}

// Newtype definition
struct DisplayPathBuf(pub PathBuf);

// Implementing Display for the newtype
impl Display for DisplayPathBuf {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0.display())
    }
}
```

![image](https://github.com/user-attachments/assets/cc2b21f1-e92b-4c79-a4f2-5d721d66234b)

**Comment by mikaelmello** [comment]
Thank you @Baarsgaard, that is the recommended pattern to use with inquire.

Previously the approach was to pass a value formatter but the new type pattern allows for better structure and is more idiomatic
