### ISSUE TITLE
When I input Chinese characters in the command line, the cursor becomes chaotic.

### ISSUE THREAD

**Issue by phostann** [mikaelmello/inquire#270]
**Describe the bug**
When I input Chinese characters in the command line, the cursor becomes chaotic. 

**To Reproduce**
```rust
let project_name = Text::new("请输入项目名称")
        .with_help_message("项目名称需要满足正则: ^[a-z][a-z0-9-]?[a-z]$")
        .prompt()?
```

**Expected behavior**
I can freely move the cursor to modify and delete the entered content.

**Screenshots**
![1](https://github.com/user-attachments/assets/8174443e-1f72-4869-8b3b-889985a1f8f2)

**Desktop (please complete the following information):**
 - OS: Macos 14.0 
 - Browser Chrome 128.0.6613.120
 - Version 0.7.5

**Additional context**
I have previously used version 0.6.2, and it worked properly.

**Comment by mikaelmello** [comment]
Thank you! I apologize, it's fixed now. It should be part of the next 0.7.6 release.
