### ISSUE TITLE
Terminal Display Height

### ISSUE THREAD

**Issue by MiniMarPaz** [mikaelmello/inquire#273]
Hello,

I've recently started using inquire library and I like it a lot. One question that I've not figured out or fount in documentation is there any possibility to expand the height of selections in terminal? I mean that more selections will be visible on terminal screen? Because right now I feel like i'm lacking a bit of height in display. Thank You for this amazing library and keep up the awesome work!
<img width="694" alt="image" src="https://github.com/user-attachments/assets/669d3fc1-b94b-4e70-afff-48c62d187f74">

**Comment by mikaelmello** [comment]
Hi @MiniMarPaz , you can use the `.with_page_size(page_size)` option when building the prompts :)
