### ISSUE TITLE
Add documentation of Text::initial_value in missing places

### ISSUE THREAD

**Issue by mikaelmello** [mikaelmello/inquire#36]
**Is your feature request related to a problem? Please describe.**

The `initial_value` property is properly documented in doc comments, but when reviewing the PR I forgot about the README (Text section) and the actual documentation of the `Text` struct, which contains an overview of the prompt API.

This is important to allow future users to easily discover this feature, in case it is useful for them.

**Describe the solution you'd like**

Simple lines describing the purpose of initial_value.

---

@irevoire pinging you in case you might be interested, but I know this is the boring part of contributing, so don't worry, I'll get to it before I release.

**Comment by mikaelmello** [comment]
Working on it already :)

**Comment by irevoire** [comment]
Thank you! I totally missed it!
