### ISSUE TITLE
Successful prompt indicator 

### ISSUE THREAD

**Issue by href** [mikaelmello/inquire#44]
**Is your feature request related to a problem? Please describe.**
When the user inputs data, the default prompt shown begins with a light-green question mark. When the input completes, that question mark remains. 

**Describe the solution you'd like**
I would love for the question mark to become a check mark or so. 

**Additional context**
Thank you for this library. I really like the prompts I’m able to create with it!

**Example (using Dialoguer)**
![](https://i.redd.it/1a8jmq5xhx981.gif)

**Comment by mikaelmello** [comment]
I really enjoyed this improvement. It should also be customizable.

What do you think about the default behavior, would you expect it to be the checkmark or the current behavior of keeping the question mark?

**Comment by href** [comment]
I personally would prefer the check mark as a default, but then that’s what I want to use anyway. For backwards compatibility I would probably leave it as is.

Another option would be for the check mark to become the default for prompts that use a validator that successfully checked the input.

**Comment by mikaelmello** [comment]
> Another option would be for the check mark to become the default for prompts that use a validator that successfully checked the input.

I can see this being a little confusing for users when there are two prompts, one with validators and one without. Validators are kind of transparent to end users unless they submit an invalid input. So if they submit everything right, it might be weird seeing one question with a checkmark and then another question maintaining the '?'.

> I personally would prefer the check mark as a default

Me too, but this affects backwards compatibility (as you mentioned) and there's no good ASCII character for checkmarks =/

It's going to be customizable then! Is this PR you'd like to make? I'm starting a new job next week so not sure I'll have the time in a while.

**Comment by href** [comment]
Sounds like a plan. Pretty new at Rust, so I likely need some help during the review process, and I don't have much time either - but I'm happy to give it a shot as soon as I get a chance.

**Comment by mikaelmello** [comment]
Hey, I've got some time to spare so I'll work on it real quick :)

**Comment by mikaelmello** [comment]
Closed via d09a62533492a8c39815d90bdfec8f03ee2d8e01

**Comment by href** [comment]
I tried it out and it worked just as I wanted. Thank you so much for your work! ❤️
