### ISSUE TITLE
Autocomplete for Text prompter doesn't seems to be working

### ISSUE THREAD

**Issue by fribeau** [mikaelmello/inquire#47]
**Describe the bug**
I can't manage to make autocomplete work with a `Text` prompter. Thinking it was my code, I cloned the repo and ran the `expense_tracker` example, but the autocomplete didn't work either.

Unlike in the [demo](https://github.com/mikaelmello/inquire/blob/main/assets/expense_tracker.gif), I didn't get any autocomplete when hitting the `tab` key with the `payee` field. Has it been broken or am I not using it correctly?

Thanks

**To Reproduce**
1. `git clone https://github.com/mikaelmello/inquire`
2. `cd inquire && cargo run --example expense_tracker --features="builtin_validators date"`
3. Try to complete the `payee` field (third field) with the `tab` key as shown in the demo
4. Autocomplete doesn't work

**Expected behavior**
Complete the input.

**Desktop (please complete the following information):**
```bash
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by mikaelmello** [comment]
Hey @fribeau.

Actually, we don't have the `tab` assigned to anything on this prompt. What I believe you're seeing in the demo was that I pressed `down arrow` to move the cursor to the first suggestion, then the prompt auto-updated the text field to the highlighted suggestion.

You bring a very good point on usability though, the tab key is widely known as associated to auto-completion, so I think it is a usability problem for us to not use it. I'm thinking of assigning `tab` to either `use the first suggestion in the list`, if none are selected, or `update text field to the current highlighted suggestion`, which would basically remove other suggestions.

**Comment by fribeau** [comment]
Thanks for this quick reply and for this awesome crate :wink: 

I also think handling `tab` would be really a great feature. 

Regarding the `tab` assignment you proposing, I know that for my use case it would not work as expected. I am trying to implement a `path` autocomplete so I am trying to reproduce the same behavior I am getting in the terminal (with `bash` for example).

If I have the following directory structure and the input is `/bar/f` I would expect `/bar/foo` when the user press the `tab` key, but not necessary the first result (`/bar/foo1`).
```bash
/bar
  /foo1
  /foo2
```

Another approach could be: 
- if only 1 suggestion remain -> complete with it
- if many -> complete with the longest prefix available 

But maybe my use case it too specific

**Comment by mikaelmello** [comment]
Yeah I think that's a little too specific for the library.

The suggestion-er behavior is implemented by the user, which means that if we hard-coded the completion process to something implementation-specific, it would break other use-cases, for example fuzzy searching and searching by substrings instead of prefixes, from the top of my mind.

What we could do instead is to have a default implementation (complete with the first option), but then provide the ability for the user to provide a hook, e.g. "auto_complete(cur_input: &str) -> String". Then you could do:

```
auto_complete = |cur_input| {
  // return string with longest prefix that matches input
}
```

Then, the prompt would call your method, get what auto-completion string and replace the current input with your completion.

There are still a few details on how to make this works seamlessly with the current "suggestion" system, but it is a direction forward :)

**Comment by fribeau** [comment]
Hey @mikaelmello

I have tried several implementations trying to come up with a good solution to this problem. I finally ended up with the solution you proposed :wink: It is a good one because it is really simple so it can really be customized to the user needs.

I opened a PR to showcase this feature. You're welcome to criticize, I am completely open to suggestions.

**Comment by mikaelmello** [comment]
@fribeau v0.3.0-alpha-2 is now up :)
