### ISSUE TITLE
Allow customization of colors in prompts.

### ISSUE THREAD

**Issue by mikaelmello** [mikaelmello/inquire#6]
**Is your feature request related to a problem? Please describe.**

> Your color palette is awful but I still need your crate, how can I make the question marks red?

**Describe the solution you'd like**

Allow lib users to customize the colors used in the prompts, something other than green for [anything, because I basically used green for all of the colorful stuff].

Could this be like a custom setting that you set once and all prompts use this config?

**Comment by shimarulin** [comment]
It would be nice to have fully customizable prompt output, like https://github.com/mitsuhiko/dialoguer/blob/3a13f16589933ad4972c3b396d3d66456d15dc6f/examples/wizard.rs#L17

**Comment by VladimirMarkelov** [comment]
By the way, is it possible(or planned) to disable colors? Kind of `--no-color` in some utilities

**Comment by mikaelmello** [comment]
>By the way, is it possible(or planned) to disable colors? Kind of --no-color in some utilities

Sure! I already implemented it in the back-end (dull method on terminal.rs) in order to make testing easier without all those modifiers. It would be just a matter of exposing it via an API, gonna create a new issue for that.

**Comment by mikaelmello** [comment]
Implemented, you can read more about it in https://github.com/mikaelmello/inquire#rendering-configuration-aka-color-themes
