### ISSUE TITLE
Add an indication that a list has extra options below (or above)

### ISSUE THREAD

**Issue by mikaelmello** [mikaelmello/inquire#8]
**Is your feature request related to a problem? Please describe.**

> Does a long list have indication that only its part is displayed? As I see from the demo, a list can be scrolled but I do not notice any clue that there are extra items above or below.

[Source](https://old.reddit.com/r/rust/comments/osa32z/announcing_inquire_a_small_library_for_building/h6n9q0m/)

**Describe the solution you'd like**

Some sort of visual indication that the list has more options not displayed at the moment, still not sure of how that would look like.

This issue affects the three prompts containing lists: select, multiselect and text (with auto-complete suggestions).

**Comment by VladimirMarkelov** [comment]
At this moment I can only suggest this: there is always a space between cursor `>` and an item. What if replace the space with `↑`(for top line) and `↓`(for bottom line) when the item is not the very first/last one? E.g, we have list ['First', 'Second', 'Third', 'Fourth', 'Fifth'] and display only 3 items at a time:

```
>↑Second
  Third
 ↓Fourth

> First
  Second
 ↓Third
```

It can be done for all lists: regular and checkbox ones.

**Comment by mikaelmello** [comment]
I thought it was a great idea and extended a bit: moving the rows one column to the right and putting simple ascii characters (`v` and `^` to indicate if there are more items below or above. Up until now I've avoided using non-ascii characters in the interface.

It looks good if the page size is large enough but a bit cluttered with small page sizes and the difference in size between "v" and "^" bothers me, here are some examples: https://asciinema.org/a/PUfZvHkio1YWve9lRbxC2cqff

On the other hand, using unicode triangles makes it look a bit better: https://asciinema.org/a/yQtrRCrUqXMhr7IM4t1M8SSAH

Still not feeling really good with the layouts though

**Comment by VladimirMarkelov** [comment]
If you even add theming feature, anybody would able to change "arrow" chracters :) Now I am agree that sticking to ASCII makes everything work everywhere and with any font.

I used unicode arrows to emphasize my idea.

**Comment by shimarulin** [comment]
In my opinion, one column also look good. When we are at the top of the list, there is no "up" triangle, and this place can be occupied by a pointer to an item in the list:

```
▶ Banana                                                                                                 
  Apple                                                                                                  
  Strawberry                                                                                             
  Grapes
▼ Lemon
```

```
  Banana                                                                                                 
  Apple                                                                                                  
▶ Strawberry                                                                                             
  Grapes
▼ Lemon
```

```
▲ Apple                                                                                                  
  Strawberry                                                                                             
▶ Grapes
  Lemon                                                                                                  
▼ Tangerine
```

```
▲ Grapes
  Lemon                                                                                                  
▶ Tangerine                                                                                              
  Watermelon                                                                                             
  Orange
```

**Comment by mikaelmello** [comment]
That's an awesome idea, I've implemented it and it looks great.

**Comment by VladimirMarkelov** [comment]
One question: How does it look in case of `Banana` is not the first and there is something above it? 
As far as I understand the idea, If there is anything hidden above or below, the cursor is always in the middle of the list? Correct? If so, that's neat. Good idea!

**Comment by mikaelmello** [comment]
> As far as I understand the idea, If there is anything hidden above or below, the cursor is always in the middle of the list? Correct?

Exactly :)

> If so, that's neat. Good idea!

Completely inspired on similar libs from other languages!

**Comment by mikaelmello** [comment]
Closed by https://github.com/mikaelmello/inquire/commit/5a74c480e3d5153f461f61519c764bead8aca3c7
