### ISSUE TITLE
Add support for highligting currently selected option

### ISSUE THREAD

**Issue by JosipTrbuscic** [mikaelmello/inquire#85]
Currently we can only change the style of all options via `RenderConfig`'s `option` field. I think it would be nice improvement to support changing the style of currently selected/higlighted option.

Something like this:
![image](https://user-images.githubusercontent.com/34209151/210361124-b16b996e-cbba-41eb-bbbe-86953d8c5b92.png)

In draft implementation I just added new option to `RenderConfig` and modified `Backend::print_option_value()` method, but I'm open for suggestions

**Comment by mikaelmello** [comment]
I think this feature is great and I'm all for it.

If you feel comfortable, please open a PR with your changes and we can refine it to the particularities of the repo before merging them!

For now, let's leave the current behavior as default (no highlighting), in the first PR to get it in without too much discussion. But if you could also create a second PR on top of that in which we could implement the default highlighting, it would be great too.

The second one has a lot of room for bikeshedding lol
