### ISSUE TITLE
Pre-populated values

### ISSUE THREAD

**Issue by mabushey** [mikaelmello/inquire#90]
This crate looks really awesome, thanks!

**Is your feature request related to a problem? Please describe.**
I have a case where I'm unable to lookup a title, so I want to present an input box with the data prefilled so for example a typo could be fixed.

**Describe the solution you'd like**
text input value pre-populated ready to edit/correct

Thanks!

**Comment by mabushey** [comment]
ahh, `..with_initial_value()`. Please add this to an example. At first I skipped over `initial_value` somehow, and then the compiler informed me it was `with_initial_value()`.

**Comment by mikaelmello** [comment]
Glad you found it!

If it may help, can you describe what other words did you think of, or places you tried to search before opening the issue? I assume the examples are one of them but anything else you'd suggest?

**Comment by mabushey** [comment]
Thanks for replying! I was probably looking for `pre-populated` or `pre-filled`.

I looked at https://docs.rs/inquire/latest/inquire/struct.Text.html
and somehow completely missed `initial_value`.

Maybe change `[Text](https://github.com/mikaelmello/inquire#Text) to get text input from the user, with built-in autocompletion support;`
to
`[Text](https://github.com/mikaelmello/inquire#Text) to get text input from the user, supporting pre-populated values and built-in autocompletion support;`
