### ISSUE TITLE
Prompt on `stderr`

### ISSUE THREAD

**Issue by b4D8** [mikaelmello/inquire#92]
Hi there, and thanks for your work on this crate!

**Is your feature request related to a problem? Please describe.**

From my understanding, it is hardcoded that prompts are sent to `stdout` (like [here](https://github.com/mikaelmello/inquire/blob/4535b38afdee62e59f05528444dffc62d0d0db10/src/terminal/crossterm.rs#L43) for crossterm).

While this may seem like a reasonable setting, I have a use case where I use a prompt to guide user into creating and submitting a bug report on **panic** and I would like to send it to `stderr` instead  so that it can't interfere with pipes.

For example, if user run `command > example.txt`, I want to be sure that the prompt won't be sent to `example.txt` if  `command` panics.

Actually, it is sometimes recommended (like [here](https://clig.dev/#output)) to _always_ send messages to `stderr`.

**Describe the solution you'd like**

A possible solution would be to let users be able to create Terminals that could be supplied to the `prompt_with_backend` methods that are currently private.

**Describe alternatives you've considered**

I am not aware of any way I could currently achieve this.

I am ready to work on a PR that let user choose, if anyone could guide me into the desired way to implement this.

Cheers!

**Comment by b4D8** [comment]
PR #89 is actually about hardcoding `stderr` instead of `stdout` which seems even better.

**Comment by mikaelmello** [comment]
Glad to have your comments supporting that PR, I'll certainly get on with making it happen.
