### ISSUE TITLE
Use &str or String instead of &'static str in RenderConfig

### ISSUE THREAD

**Issue by arturfast** [mikaelmello/inquire#95]
**Is your feature request related to a problem? Please describe.**
I'd like to customize my prompt prefix in the [Text menu](https://docs.rs/inquire/latest/inquire/struct.Text.html#) using the format! macro. This is not possible due to prompt_prefix being defined as a &'static str in [RenderConfig](https://docs.rs/inquire/latest/src/inquire/ui/render_config.rs.html#28). This is limiting because I can only pass string literals instead of formatted Strings or &str.  

**Describe the solution you'd like**
I'd like to change the parameters of all the fields in RenderConfig, particulary prompt_prefix, to either String or &str. Alternatively I'd like to learn if there is any particular reason for it only accepting string literals.  

**Describe alternatives you've considered**
I have tried various ways to convert a String to a &'static str but they all fail due to lifetimes. [Here](https://stackoverflow.com/questions/48720914/convert-format-from-string-to-static-str), [here](https://stackoverflow.com/questions/61071308/how-to-pass-a-variable-as-a-string-literal-in-rust), and [here](https://stackoverflow.com/questions/60876226/understanding-error-borrowed-value-does-not-live-long-enough) are some of the stackoverflow questions regarding this. I also tried to concatenate string literals and pass the result, without success. Another method I tried was `Box::leak(format!("{}", "Hello world").into_boxed_str());
 `, but it didn't work, and it's a dirty solution that leaks memory.   

**Additional context**

**Comment by mikaelmello** [comment]
I see you, I'll figure something out and make it possible!
